version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:18-bullseye
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    working_dir: /workspaces/${localWorkspaceFolderBasename}
    command: sleep infinity
    network_mode: service:mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
