services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-18-bullseye
    command: bash -c 'npm install && npm start'
    working_dir: /app
    network_mode: service:mysql
    volumes:
      - ./package.json:/app/package.json
      - ./app.js:/app/app.js
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
